# <center> Home assignment 4. Pandas </center>

In [1]:
import pandas as pd

From [World Health Organization](https://www.who.int/emergencies/diseases/novel-coronavirus-2019) - On 31 December 2019, WHO was alerted to several cases of pneumonia in Wuhan City, Hubei Province of China. The virus did not match any other known virus. This raised concern because when a virus is new, we do not know how it affects people. So daily level information on the affected people can give some interesting insights when it is made available to the broader data science community.

This data set (```covid_19_data_ha4.csv```) has daily level information on the number of affected cases, deaths, and recovery from the 2019 novel coronavirus. Please note that this is time-series data and so the number of cases on any given day is the cumulative number. The data is available from 22 January 2020.

The data source for more details: https://www.kaggle.com/sudalairajkumar/novel-corona-virus-2019-dataset?select=covid_19_data.csv

By the way, [Johns Hopkins University](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6) has made an excellent dashboard using the affected cases from this data set.

**Task 1** [1 point]. Read the data set ```covid_19_data_ha4.csv``` into DataFrame using pandas library, change a parameter for making the first column (```SNo```) to be the index of out table, and save a variable ```df``` for addressing to this table (DataFrame) in the next steps. Return the first 20 rows in the output and have a look at what is inside this table.

In [22]:
df = pd.read_csv('covid_19_data_ha4.csv', delimiter=',')

df = df.set_index('SNo')
df.head(20)

,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
SNo,,,,,,,
1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,NaN,0.0,0.0
6,01/22/2020,Guangdong,Mainland China,1/22/2020 17:00,26.0,0.0,0.0
7,01/22/2020,Guangxi,Mainland China,1/22/2020 17:00,2.0,0.0,0.0
8,01/22/2020,Guizhou,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
9,01/22/2020,Hainan,Mainland China,1/22/2020 17:00,4.0,0.0,0.0
10,01/22/2020,Hebei,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
11,01/22/2020,Heilongjiang,Mainland China,1/22/2020 17:00,NaN,0.0,0.0
12,01/22/2020,Henan,Mainland China,1/22/2020 17:00,5.0,0.0,0.0
13,01/22/2020,Hong Kong,Hong Kong,1/22/2020 17:00,0.0,0.0,0.0
14,01/22/2020,Hubei,Mainland China,1/22/2020 17:00,444.0,17.0,28.0
15,01/22/2020,Hunan,Mainland China,1/22/2020 17:00,4.0,0.0,0.0
16,01/22/2020,Inner Mongolia,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
17,01/22/2020,Jiangsu,Mainland China,1/22/2020 17:00,NaN,0.0,0.0
18,01/22/2020,Jiangxi,Mainland China,1/22/2020 17:00,2.0,0.0,0.0
19,01/22/2020,Jilin,Mainland China,1/22/2020 17:00,NaN,0.0,0.0
20,01/22/2020,Liaoning,Mainland China,1/22/2020 17:00,2.0,0.0,0.0

**Task 2** [2 points]. Look at the size of this data set (how many rows and columns it contains).Check the data types for all columns and get descriptive statistics for all of them.

*Hint*: You can summarize the numeric and text columns separately, or compile one summary that includes all data types.

In [39]:
# Your code here

df_row = df.shape[0]
df_columns = df.shape[1]
df_stats = df.dtypes

print(f'The amount of rows:{df_row}\n')
print(f'The amount of columns:{df_columns}\n')
print(df_stats,'\n')
print(df.describe())

The amount of rows:236017

The amount of columns:8

ObservationDate    datetime64[ns]
Province/State             object
Country/Region             object
Last Update                object
Confirmed                 float64
Deaths                    float64
Recovered                 float64
Recovered Ratio           float64
dtype: object

          Confirmed         Deaths     Recovered  Recovered Ratio
count  1.572340e+05  236017.000000  2.360170e+05    226909.000000
mean   5.742544e+04    1487.719368  3.393027e+04        77.282532
std    1.849079e+05    4770.414639  1.474800e+05        38.012443
min    0.000000e+00    -178.000000 -8.544050e+05         0.000000
25%    7.280000e+02       9.000000  1.000000e+01        86.400000
50%    6.675500e+03     127.000000  1.224000e+03        96.976048
75%    3.348300e+04     880.000000  1.263900e+04        98.647242
max    3.664050e+06  108208.000000  6.399531e+06       100.059140

**Task 3** [3 points]. Answer the following questions using the descriptive statistics report (from Task 2):

| Questions | 
| :--- |
| 1. How many countries covers this data set on COVID-19? |
| 2. On what observation date the table contains the most information (the greatest number of rows)?  |
| 3. What is the median  for the number of deaths?|


*Remark*: 

If you see numbers in your table in exponential format, for instance, 2.360170e+05, you can convert them to floating point for convenience:

```python 
>>> float(2.360170e+05)
236017.0
```

In [4]:
# Your answers here (it is better to change the format of this cell to Markdown)

#question 1
unique_country = len(df['Country/Region'].unique())

print(f'The amount of countries is: {unique_country}')
 
#question 2    
most_date = df['ObservationDate'].value_counts()[:1]

print(f'The most frequent date: {most_date}')
    
#question 3    
deaths = df['Deaths'].median()
print(f'Median for the number of deaths:{deaths}')

The amount of countries is: 227
The most frequent date: 02/23/2021    764
Name: ObservationDate, dtype: int64
Median for the number of deaths:127.0

**Task 4** [1 point]. Recall a method that we used for getting counts for unique rows in the DataFrame.
Select a column with observation dates and return the distribution how many rows are in this table for each date. Make it in ascending order and select top 50 rows.

Now, you are able to see how many states and countries were confirmed to have COVID-19 starting from 22 January 2020 for the first 50 days.

In [5]:
# Your code here
df['ObservationDate'].value_counts().sort_values()[:50]

01/22/2020     38
01/24/2020     41
01/25/2020     44
01/23/2020     46
01/26/2020     47
01/27/2020     51
01/28/2020     52
01/29/2020     54
01/30/2020     58
01/31/2020     62
02/01/2020     67
02/02/2020     67
02/03/2020     68
02/04/2020     70
02/05/2020     71
02/06/2020     71
02/09/2020     72
02/07/2020     72
02/10/2020     72
02/08/2020     72
02/11/2020     73
02/12/2020     73
02/13/2020     74
02/18/2020     75
02/15/2020     75
02/14/2020     75
02/16/2020     75
02/17/2020     75
02/19/2020     76
02/20/2020     76
02/22/2020     84
02/21/2020     84
02/23/2020     85
02/24/2020     90
02/25/2020     94
02/26/2020    101
02/27/2020    105
02/28/2020    114
02/29/2020    119
03/01/2020    125
03/02/2020    141
03/03/2020    151
03/04/2020    160
03/05/2020    173
03/06/2020    199
03/10/2020    206
03/11/2020    216
03/12/2020    218
03/07/2020    225
03/13/2020    230
Name: ObservationDate, dtype: int64

**Task 5** [3 points]. Check for each column how many missing values there are. 
For the columns with missing values using the method ```fillna()```. If the column has object data type (string), then replace each missing value in-place with a string 'Unknown'. If it has a float data type, replace each missing value in-place with the median value in this column. For finding the median for a particular column you can use ```df[column_name].median()```.

Re-check that now you have no missing values in a table.

In [15]:
df['Province/State'].fillna("Unknown", inplace = True)
df['Confirmed'] = df['Confirmed'].fillna((df['Confirmed'].median()))
df.isnull().sum(axis = 0)

ObservationDate    0
Province/State     0
Country/Region     0
Last Update        0
Confirmed          0
Deaths             0
Recovered          0
dtype: int64

**Bonus task [3 points]**. 

1. Create a new column called Recovered Ratio with the percentage of recovered cases out of all closed cases (both recoveries and deaths). Replace missing values in a new column by 0.0. 
2. Filter the table by two conditions: 1) only the data on the last recent available date should be left 2) the recovered ratio should be more than 0. 
3. Sort this filtered table of data by the recovered ratio in ascending order. The population of which 10 countries suffered (based on the recovered ratio) the most?

In [36]:
import datetime as datetime


df['Recovered Ratio'] = 100 / (df.loc[:, 'Deaths':'Recovered'].sum(1)/df['Recovered'])
df['ObservationDate'] = pd.to_datetime(df['ObservationDate'])

df = df.sort_values(by = 'ObservationDate',ascending=False)
df

,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Recovered Ratio
SNo,,,,,,,,
236017,2021-02-27,Zuid-Holland,Netherlands,2021-02-28 05:22:20,255335.0,3732.0,0.0,0.000000
235971,2021-02-27,Varmland,Sweden,2021-02-28 05:22:20,NaN,167.0,0.0,0.000000
235887,2021-02-27,Sergipe,Brazil,2021-02-28 05:22:20,150533.0,2955.0,141391.0,97.952836
235636,2021-02-27,Ivano-Frankivsk Oblast,Ukraine,2021-02-28 05:22:20,NaN,1164.0,48938.0,97.676739
236014,2021-02-27,Zeeland,Netherlands,2021-02-28 05:22:20,16480.0,178.0,0.0,0.000000
...,...,...,...,...,...,...,...,...
3,2020-01-22,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0,NaN
2,2020-01-22,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0,NaN
11,2020-01-22,Heilongjiang,Mainland China,1/22/2020 17:00,NaN,0.0,0.0,NaN
19,2020-01-22,Jilin,Mainland China,1/22/2020 17:00,NaN,0.0,0.0,NaN
1,2020-01-22,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0,NaN